# Project 3 : Guess The Number (User),
# Created By Huzaifa Ghouri (419013)


import random

def user_guess():
    # User guesses a random number generated by the computer.

    print("I'm thinking of a number between 1 and 50.")
    print("Try to guess my number!")
    name = input("But First Enter Your Name")

    secret_number = random.randint(1, 50)  # Computer picks a random number
    attempts = 0

    while True:
        try:
            guess = int(input("Enter your guess: "))
            attempts += 1 # Attempts Count

            if guess < secret_number:
                print("Too low!")
            elif guess > secret_number:
                print("Too high!")
            else:
                print(f"Congratulations..! {name} My Number Was {guess} You Guessed My Number in {attempts} Attempts!")
                break  # Exit the loop when the guess is correct

        except ValueError:
            print("Invalid input. Please enter a number.")

if __name__ == "__main__":
    user_guess()